- hosts: netscaler
  remote_user: nsroot
  connection: citrix.adc.ssh_citrix_adc
  gather_facts: False
  vars:
    ansible_python_interpreter: /var/python/bin/python

    build_location: "/var/nsinstall/new_build/"
    build_file_name: "build-13.1-34.11_nc_64.tgz"

  tasks:
    - name: Untar
      shell: "tar xvf {{ build_location }}{{ build_file_name }} -C {{ build_location }}"

    - name: Install Ns build
      shell: "./installns -Y"
      args:
        chdir: "{{ build_location }}"
      async: 120
      poll: 0

    - name: Wait for the reboot to complete.
      wait_for_connection:
        connect_timeout: 10
        sleep: 10
        delay: 120
        timeout: 900

